export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const ADVERTS_LOADED_REQUEST = 'ADVERTS_LOADED_REQUEST';
export const ADVERTS_LOADED_SUCCESS = 'ADVERTS_LOADED_SUCCESS';
export const ADVERTS_LOADED_FAILURE = 'ADVERTS_LOADED_FAILURE';

export const ADVERTS_CREATED_REQUEST = 'ADVERTS_CREATED_REQUEST';
export const ADVERTS_CREATED_SUCCESS = 'ADVERTS_CREATED_SUCCESS';
export const ADVERTS_CREATED_FAILURE = 'ADVERTS_CREATED_FAILURE';

export const ADVERTS_DETAIL_REQUEST = 'ADVERTS_DETAIL_REQUEST';
export const ADVERTS_DETAIL_SUCCESS = 'ADVERTS_DETAIL_SUCCESS';
export const ADVERTS_DETAIL_FAILURE = 'ADVERTS_DETAIL_FAILURE';

export const ADVERTS_DELETED_REQUEST = 'ADVERTS_DELETED_REQUEST';
export const ADVERTS_DELETED_SUCCESS = 'ADVERTS_DELETED_SUCCESS';
export const ADVERTS_DELETED_FAILURE = 'ADVERTS_DELETED_FAILURE';

export const TAGS_LOADED = 'TAGS_LOADED';

export const UI_RESET_ERROR = 'UI_RESET_ERROR';
